version: '3.8'
services:
  node:
    container_name: node_server
    build: ./back-end
    env_file:
      - ./back-end/.env
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - postgres
      - node
      - react

  openssl:
    image: ./openssl
    container_name: openssl
    volumes:
    - ssl-certs:/certs
    - react-volume:/var/www/html
    command: certonly --webroot --agree-tos --email you@example.com -w /var/www/html -d example.com -d www.example.com

volumes:
  postgres-volume:
  react-volume:
  ssl-certs:
